const happyRoutesInfo = [
  {
    link: "/api/happy",
    type: "GET",
    get: true,
    template: "/api/happy",
    purpose: "gets all happy",
    backendtest: "yes",
    frontendconnect: "happyPage",
    notes: "implemented in",
  },
  {
    link: "/api/happy/2",
    type: "GET",
    get: true,
    template: "/api/happy/:id",
    purpose: "get specific happy",
    backendtest: "yes",
    notes: "implemented in",
  },
  {
    link: "/api/happy",
    type: "POST",
    template: "/api/happy",
    purpose: "post happy",
    backendtest: "yes",
    notes: "",
  },
  //   {
  //     link: "/api/users/2/search/asdf",
  //     type: "GET",
  //     get: true,
  //     template: "/api/users/:userId/search/:search",
  //     purpose: "gets search content",
  //     backendtest: "yes",
  //     notes: "implemented in",
  //   },
  //   {
  //     link: "/api/users/2/search",
  //     type: "GET",
  //     get: true,
  //     template: "/api/users/:userId/search",
  //     purpose: "gets initial search content",
  //     backendtest: "yes",
  //     notes: "implemented in",
  //   },
  {
    link: "/api/happy/2",
    type: "PUT",
    template: "/api/happy/:id - newhappy is request.body",
    purpose: "edit happy",
    backendtest: "yes",
    frontendconnect: "",
    notes: "implemented in",
  },
  {
    link: "/api/happy/2",
    type: "DELETE",
    template: "/api/happy/:id",
    purpose: "delete happy",
    backendtest: "yes",
    frontendconnect: "no",
    notes: "implemented in",
  },
];
module.exports = { happyRoutesInfo };
